//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("Service.Employees", ClrNamespace="Service.Employees")]

namespace Service.Employees
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="Service.Employees")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shared.Entities.FullTimeEmployee))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Shared.Entities.PartTimeEmployee))]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmployeeIdField;
        
        private string NameField;
        
        private System.DateTime StartDateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeId
        {
            get
            {
                return this.EmployeeIdField;
            }
            set
            {
                this.EmployeeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
}

/*namespace Shared.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class FullTimeEmployee : Service.Employees.Employee
    {
        
        private int SalaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Salary
        {
            get
            {
                return this.SalaryField;
            }
            set
            {
                this.SalaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartTimeEmployee", Namespace="http://schemas.datacontract.org/2004/07/Shared.Entities")]
    public partial class PartTimeEmployee : Service.Employees.Employee
    {
        
        private double HourlyRateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HourlyRate
        {
            get
            {
                return this.HourlyRateField;
            }
            set
            {
                this.HourlyRateField = value;
            }
        }
    }
}*/


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ServiceLayer", ConfigurationName="IServiceEmployees")]
public interface IServiceEmployees
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/AddEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/AddEmployeeResponse")]
    void AddEmployee(Service.Employees.Employee emp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/AddEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/AddEmployeeResponse")]
    System.Threading.Tasks.Task AddEmployeeAsync(Service.Employees.Employee emp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/DeleteEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/DeleteEmployeeResponse")]
    void DeleteEmployee(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/DeleteEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/DeleteEmployeeResponse")]
    System.Threading.Tasks.Task DeleteEmployeeAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/UpdateEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/UpdateEmployeeResponse")]
    void UpdateEmployee(Service.Employees.Employee emp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/UpdateEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/UpdateEmployeeResponse")]
    System.Threading.Tasks.Task UpdateEmployeeAsync(Service.Employees.Employee emp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/GetAllEmployees", ReplyAction="http://ServiceLayer/IServiceEmployees/GetAllEmployeesResponse")]
    Service.Employees.Employee[] GetAllEmployees();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/GetAllEmployees", ReplyAction="http://ServiceLayer/IServiceEmployees/GetAllEmployeesResponse")]
    System.Threading.Tasks.Task<Service.Employees.Employee[]> GetAllEmployeesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/GetEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/GetEmployeeResponse")]
    Service.Employees.Employee GetEmployee(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/GetEmployee", ReplyAction="http://ServiceLayer/IServiceEmployees/GetEmployeeResponse")]
    System.Threading.Tasks.Task<Service.Employees.Employee> GetEmployeeAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/CalcPartTimeEmployeeSalary", ReplyAction="http://ServiceLayer/IServiceEmployees/CalcPartTimeEmployeeSalaryResponse")]
    double CalcPartTimeEmployeeSalary(int idEmployee, int hours);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ServiceLayer/IServiceEmployees/CalcPartTimeEmployeeSalary", ReplyAction="http://ServiceLayer/IServiceEmployees/CalcPartTimeEmployeeSalaryResponse")]
    System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceEmployeesChannel : IServiceEmployees, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceEmployeesClient : System.ServiceModel.ClientBase<IServiceEmployees>, IServiceEmployees
{
    
    public ServiceEmployeesClient()
    {
    }
    
    public ServiceEmployeesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceEmployeesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceEmployeesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceEmployeesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AddEmployee(Service.Employees.Employee emp)
    {
        base.Channel.AddEmployee(emp);
    }
    
    public System.Threading.Tasks.Task AddEmployeeAsync(Service.Employees.Employee emp)
    {
        return base.Channel.AddEmployeeAsync(emp);
    }
    
    public void DeleteEmployee(int id)
    {
        base.Channel.DeleteEmployee(id);
    }
    
    public System.Threading.Tasks.Task DeleteEmployeeAsync(int id)
    {
        return base.Channel.DeleteEmployeeAsync(id);
    }
    
    public void UpdateEmployee(Service.Employees.Employee emp)
    {
        base.Channel.UpdateEmployee(emp);
    }
    
    public System.Threading.Tasks.Task UpdateEmployeeAsync(Service.Employees.Employee emp)
    {
        return base.Channel.UpdateEmployeeAsync(emp);
    }
    
    public Service.Employees.Employee[] GetAllEmployees()
    {
        return base.Channel.GetAllEmployees();
    }
    
    public System.Threading.Tasks.Task<Service.Employees.Employee[]> GetAllEmployeesAsync()
    {
        return base.Channel.GetAllEmployeesAsync();
    }
    
    public Service.Employees.Employee GetEmployee(int id)
    {
        return base.Channel.GetEmployee(id);
    }
    
    public System.Threading.Tasks.Task<Service.Employees.Employee> GetEmployeeAsync(int id)
    {
        return base.Channel.GetEmployeeAsync(id);
    }
    
    public double CalcPartTimeEmployeeSalary(int idEmployee, int hours)
    {
        return base.Channel.CalcPartTimeEmployeeSalary(idEmployee, hours);
    }
    
    public System.Threading.Tasks.Task<double> CalcPartTimeEmployeeSalaryAsync(int idEmployee, int hours)
    {
        return base.Channel.CalcPartTimeEmployeeSalaryAsync(idEmployee, hours);
    }
}
